### ISSUE TITLE
Logs are in alphabetical order when tests fail

### ISSUE THREAD

**Issue by brycahta** [aws/amazon-ec2-instance-selector#100]
* The e2e test [sorts](https://github.com/aws/amazon-ec2-instance-selector/blob/main/test/e2e/run-test#L17) the expected and actual test values when comparing results. This works when the tests pass, but when the tests fail the logs are also returned sorted making them unreadable.

* [Example](https://github.com/aws/amazon-ec2-instance-selector/runs/2957071752?check_suite_focus=true):
```
	🔺ACTUAL: - - - - --region AWS_DEFAULT_REGION AWS_REGION Unable a default environment environment find flag in in places: profile region region the to usual variable variable ~/.aws/config
	🔺Expected: t3a.micro t3.micro t2.micro
```

**Comment by bwagner5** [comment]
fixed
