### ISSUE TITLE
Bug - Invalid filtering type with service eks

### ISSUE THREAD

**Issue by vikas027** [aws/amazon-ec2-instance-selector#108]
This is an excellent tool. Thanks for creating it :)

I have filtered valid instances for `eks` like this but EKS complained that instance `c6i.xlarge` is not a supported one. I am using terraform resource `aws_eks_node_group`

```bash
❯ ec2-instance-selector --version
v2.0.3

❯ ec2-instance-selector --service eks --memory 8 --vcpus 4 --cpu-architecture x86_64 -r ap-southeast-2
c5.xlarge
c5a.xlarge
c5ad.xlarge
c5d.xlarge
c6i.xlarge
inf1.xlarge
```

**Comment by bwagner5** [comment]
Are you using a Managed Node Group?

**Comment by vikas027** [comment]
Yes, I am using managed node groups. It failed when I had used Terraform to provision my code, which uses AWS APIs directly.

**Comment by suket22** [comment]
I wasn't able to replicate your issue with Managed Nodegroups. I used the AWS CLI to create a nodegroup with `c6i.xlarge` and my nodes are healthy. 

What's the specific error you're getting back from the CreateNodegroup API? You can find me on the Kubernetes Slack too if  that would be faster.

**Comment by tdeheurles** [comment]
Hey,

I'm having the [same problem with eksctl that is using amazon-ec2-instance-selector](https://github.com/weaveworks/eksctl/issues/4544).

I'm looking for `managed node group`, `4cpu`, `8mem` in `eu-west-2`, and this also results in `c6i.xlarge that is refused` by the node group. I'm using the latest eksctl version 0.76.0. (Sorry I can't say which version of aws-ec2-instance-selector they are using at the moment).

**Comment by tdeheurles** [comment]
> 

Hey, can you provide more details on the configuration you did use to start you node group please ? I tried to update AMI to the latest version without success, the same error did happen. At the moment, I didn't see any c6 started with node groups.

We have an uncompatibility with EKS atm.

Note that, to me, aws-ec2-instance-selector behaviour seems correct, maybe eksctl needs to provide a different filtering when using aws-ec2-selector so we maintain that compatibility.

**Comment by tdeheurles** [comment]
Hey @bwagner5 @suket22 @vikas027 , as confirmed [there](https://github.com/weaveworks/eksctl/issues/4544#issuecomment-1017307302), I think this ticket could be closed as resolved now no ?

**Comment by vikas027** [comment]
Sure, we can close the ticket now.
