### ISSUE TITLE
Add support for EC2 Multicard

### ISSUE THREAD

**Issue by amrragab8080** [aws/amazon-ec2-instance-selector#115]
On d1.24xlarge and p4d.24xlarge  the reference to the 4x100 Gigabit networking is because of a feature called EC2 Multicard. It might be easier to just add a column called EC2Multicard Support with the number of multicards supported which in this case for dl1 and p4d is 4. Future instances will support this and this feature will continue to expand.
```
Instance Type  VCPUs   Mem (GiB)  Hypervisor  Current Gen  Hibernation Support  CPU Arch  Network Performance  ENIs    GPUs    GPU Mem (GiB)  GPU Info             On-Demand Price/Hr           
-------------  -----   ---------  ----------  -----------  -------------------  --------  -------------------  ----    ----    -------------  --------             ------------------           
dl1.24xlarge   96      768        nitro       true         false                x86_64    4x 100 Gigabit       60      8       256            Habana Gaudi HL-205  -No Price Filter Specified-
p4d.24xlarge   96      1,152      nitro       true         false                x86_64    4x 100 Gigabit       60      8       320            NVIDIA A100          -No Price Filter Specified-
```

**Comment by bwagner5** [comment]
The columns are currently pretty sacred space until we add the feature to specify which columns you want to show. I actually kind of like the minimal way it is formatted here as `4x 100 Gigabit`.
