### ISSUE TITLE
sort by price

### ISSUE THREAD

**Issue by matti** [aws/amazon-ec2-instance-selector#122]
usacase

```
ec2-instance-selector --region=eu-north-1 \
                --vcpus-max=2 \
                --memory-max=2 \
                --cpu-architecture x86_64 \
                --gpus 0 \
                --root-device-type ebs
```
returns 3 instances - which one is the cheapest?

**Comment by digocorbellini** [comment]
@matti Instance type sorting has now been implemented for multiple instance fields (including spot and on demand price)! Checkout the readme for an example of its use: [CLI Examples](https://github.com/aws/amazon-ec2-instance-selector#cli)
