### ISSUE TITLE
Instance types not supported by EMR

### ISSUE THREAD

**Issue by christianhxc** [aws/amazon-ec2-instance-selector#135]
When running a command like the following, it's returning `m5n.2xlarge` and `m5ad.2xlarge` which are not supported by EMR.

```
ec2-instance-selector --vcpus-min 8 --vcpus-max 8 --vcpus-to-memory-ratio 1:4 --cpu-architecture x86_64 --current-generation --gpus 0 --service emr-5.32.0 --max-results 50 -o table-wide --price-per-hour-max 0.428 -u spot --region eu-west-1
```

Do we need to specify another parameter or is there an issue with the API call?

**Comment by bwagner5** [comment]
The EMR service integration is not the best tbh.  To my knowledge there is no API to determine which instance types are supported for EMR, just the docs page which is pretty difficult to read.  It may be worth deprecating the EMR service integration.  

Here's the current logic: https://github.com/aws/amazon-ec2-instance-selector/blob/main/pkg/selector/emr.go

**Comment by christianhxc** [comment]
@bwagner5 thanks for the feedback, I thought it was a parameter being forwarded to the API but I see the list is hard coded. So, in the meantime, should we exclude types that are not supported as we get feedback?

**Comment by bwagner5** [comment]
We can do that. Are you able to submit a PR with more accurate instance types list per version?

**Comment by christianhxc** [comment]
@bwagner5 sure, I'll work on updating the instance types for EMR
