### ISSUE TITLE
Pricing API change in aws-sdk-go

### ISSUE THREAD

**Issue by hakman** [aws/amazon-ec2-instance-selector#137]
When updating kOps dependencies, there is a failure related to `amazon-ec2-instance-selector`:
https://github.com/kubernetes/kops/actions/runs/2594660135
```
vendor/github.com/aws/amazon-ec2-instance-selector/v2/pkg/ec2pricing/odpricing.go#L172
cannot use priceDoc (variable of type *string) as type aws.JSONValue in argument to c.parseOndemandUnitPrice
```

Most likely, it would have been noticed when projects deps would have been updated also, but if anyone could look into this, it would be appreciated.

**Comment by bwagner5** [comment]
We'll look into this and get a fix out ASAP

**Comment by hakman** [comment]
Thanks @bwagner5! 😄

**Comment by bwagner5** [comment]
Should be resolved now
