### ISSUE TITLE
Support for AWS_PROFILE env var and shared configuration cred setup

### ISSUE THREAD

**Issue by ruecarlo** [aws/amazon-ec2-instance-selector#14]
At the moment the CLI does not support the use of shared configuration credentials setup (https://github.com/aws/aws-sdk-go#configuring-credentials) and selecting the aws profile by using the standard AWS_PROFILE environment variable.

To make the shared config credentials, I just had to set up the environment variable "AWS_SDK_LOAD_CONFIG=1" and as per the documentation pass the parameter "--profile". Although I could use `--profile $AWS_PROFILE` to pass the profile, ideally I'd like for that to be implicit, like in the aws cli.

**Comment by bwagner5** [comment]
released update https://github.com/aws/amazon-ec2-instance-selector/releases/tag/v1.2.0
