### ISSUE TITLE
--cpu-manufacturer intel shows AMD EPYC based c5ad and m5ad

### ISSUE THREAD

**Issue by atamgp** [aws/amazon-ec2-instance-selector#162]
`ec2-instance-selector  --cpu-manufacturer intel --vcpus 16 --vcpus-to-memory-ratio 1:2 --cpu-architecture x86_64 --hypervisor nitro --ebs-optimized --network-performance-min 5 --usage-class spot --service eks --region eu-central-1 -o table-wide --sort-by spot-price`

This lists c5ad.4xlarge.. same for m5ad with --vcpus-to-memory-ratio 1:4
https://aws.amazon.com/blogs/aws/new-amd-epyc-powered-amazon-ec2-m5ad-and-r5ad-instances/

**Comment by hfastek** [comment]
Hi @atamgp 
problem was fixed in v.2.4.1
