### ISSUE TITLE
Unable to connect to EC2 instance 

### ISSUE THREAD

**Issue by Dr-Django** [aws/amazon-ec2-instance-selector#339]
![i-005c715f733d3a96a(1)](https://github.com/aws/amazon-ec2-instance-selector/assets/131945810/ba3d7392-8e54-44c4-b2de-455a4b4bbe77)

I have shared my ec2 instance screenshot, I am unable to connect to my ec2 instance using console. I have lost my key pair file as well, so i am unable to access it. Let me share error message getting on console:

![image](https://github.com/aws/amazon-ec2-instance-selector/assets/131945810/21c2ab34-6de7-4dcb-a3f4-eea2528db6f3)

Moreover, SSH in-bound traffic rule is allowed in my security-group. I don't know to resolve this issue, i tried to reboot instance many times but didn't work for me. Do you guys have any suggest to get out of it. Thanks for focusing

**Comment by bwagner5** [comment]
This tool is only for instance selection filtering, not launching or connecting
