### ISSUE TITLE
Support unsetting select filter flags with the usage of Suite Flags

### ISSUE THREAD

**Issue by pdk27** [aws/amazon-ec2-instance-selector#48]
Suite Flags is a good simplification for common / popular use cases. Overriding of values set for filter flags when suite flags are used is allowed, however, there is no way to unset certain filter flags like 

```
ec2-instance-selector --base-instance-type m4.xlarge -o table --unset=memory-max,vcpus-max
```

**Comment by bwagner5** [comment]
no traction on this and it is at least possible by overriding to min and max vals
