### ISSUE TITLE
Sluggishness of t3.a EC2 instance

### ISSUE THREAD

**Issue by deekshith-elear** [aws/amazon-ec2-instance-selector#53]
Hi,
I had launched a t3a.large instance to deploy our microservices. The Available RAM of the ec2 instance is around 4GB and CPU usage is not more than 40% most of the time[As per cloud watch monitoring details]. But, Deployed microservices are providing a delayed response compared to microservices running in other instances. Even SSH to the server is taking more than 10 seconds.

can anyone help me to identify the root cause of the sluggishness?

**Comment by bwagner5** [comment]
@deekshith-elear  

`t*` instance types are burstable, so that may be your issue. But please note that issues you open on this repo should be about the amazon-ec2-instance-selector CLI/SDK. If you're having problems with EC2, please open an AWS support ticket from your AWS account.
