### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by Higherings** [aws/amazon-ec2-instance-selector#79]
Hello,
Is there a way to run this utility on Windows? It will be great to have this for windows too.

**Comment by bwagner5** [comment]
Do you mean run the tool on a windows machine, or do you mean filter on instance types that support Windows? 

If you'd like to run the tool on your windows laptop or desktop, you can download the windows binary: https://github.com/aws/amazon-ec2-instance-selector/releases/download/v2.0.2/ec2-instance-selector-windows-amd64

**Comment by Higherings** [comment]
Yes, run the tool on Windows platform.
Thank you, I missed completely the downloads.
You should update the README to point in that direction for windows users.

Thanks again.
